Repository issue-tracker-team-01/issue-tracker, pull requests merged in 2023-05, with the labels that each got.

#3 초기 설정 및 프로젝트 생성
  iOS/.gitignore
  iOS/Issue-tracker/.swiftlint.yml
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Issue-tracker/Issue-tracker.xcworkspace/contents.xcworkspacedata
  iOS/Issue-tracker/Issue-tracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Issue-tracker/Issue-tracker/AppDelegate.swift
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/Contents.json
  iOS/Issue-tracker/Issue-tracker/Base.lproj/LaunchScreen.storyboard
  iOS/Issue-tracker/Issue-tracker/Base.lproj/Main.storyboard
  iOS/Issue-tracker/Issue-tracker/Info.plist
  iOS/Issue-tracker/Issue-tracker/SceneDelegate.swift
  iOS/Issue-tracker/Issue-tracker/ViewController.swift
  iOS/Issue-tracker/Podfile
  iOS/Issue-tracker/Podfile.lock
Labels: Setting, iOS

#7 원활한 씬 이동을 위한 탭바 생성
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/레이블.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/레이블.imageset/레이블.svg
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/마일스톤.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/마일스톤.imageset/마일스톤.svg
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/이슈.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/이슈.imageset/이슈.svg
  iOS/Issue-tracker/Issue-tracker/Base.lproj/Main.storyboard
  iOS/Issue-tracker/Issue-tracker/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
Labels: iOS, Feature

#8 [FE] 프로젝트 초기 환경 설정
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc.json
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/mockServiceWorker.js
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.js
  fe/src/App.test.js
  fe/src/index.css
  fe/src/index.js
  fe/src/logo.svg
  fe/src/mocks/handler.js
  fe/src/mocks/worker.js
  fe/src/reportWebVitals.js
  fe/src/setupTests.js
Labels: Setting, FE

#9 이슈리스트 컬렉션뷰 작업
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/AppDelegate.swift
  iOS/Issue-tracker/Issue-tracker/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
Labels: iOS, Feature, Design

#12 이슈추가버튼 생성
  iOS/.gitignore
  iOS/Issue-tracker/.swiftlint.yml
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Issue-tracker/Issue-tracker.xcworkspace/contents.xcworkspacedata
  iOS/Issue-tracker/Issue-tracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Issue-tracker/Issue-tracker/AppDelegate.swift
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/레이블.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/레이블.imageset/레이블.svg
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/마일스톤.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/마일스톤.imageset/마일스톤.svg
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/이슈.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Assets.xcassets/이슈.imageset/이슈.svg
  iOS/Issue-tracker/Issue-tracker/Base.lproj/LaunchScreen.storyboard
  iOS/Issue-tracker/Issue-tracker/Base.lproj/Main.storyboard
  iOS/Issue-tracker/Issue-tracker/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/CreateIssueButton.swift
  iOS/Issue-tracker/Issue-tracker/Info.plist
  iOS/Issue-tracker/Issue-tracker/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/SceneDelegate.swift
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
  iOS/Issue-tracker/Podfile
  iOS/Issue-tracker/Podfile.lock
Labels: iOS, Feature, Design

#17 docs: README 작성
  BE/README.md
Labels: Setting, BE

#19 [BE] DB 모델링 : 요구사항 분석서 작성
  BE/요구사항분석.md
Labels: Setting, BE

#20 docs: 요구사항분석 수정
  BE/요구사항분석.md
Labels: Setting, BE

#21 I os/custom cell
  iOS/Issue-tracker/Issue-tracker/IssueCell.swift
Labels: iOS, Feature, Design

#24 폰트 다운로드 및 세팅
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/Info.plist
  iOS/Issue-tracker/Issue-tracker/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
  iOS/Issue-tracker/SF-Pro-Display-Bold.otf
  iOS/Issue-tracker/SF-Pro-Display-Medium.otf
  iOS/Issue-tracker/SF-Pro-Display-Regular.otf
  iOS/Issue-tracker/SF-Pro-Display-Semibold.otf
Labels: iOS, Feature, Design

#26 [iOS] 이슈생성버튼 구현
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/ViewController.swift
Labels: iOS, Feature, Design

#31 [iOS] issueCell 구현
  iOS/Issue-tracker/Issue-tracker/IssueCell.swift
  iOS/Issue-tracker/Podfile
Labels: iOS, Feature

#38 [FE] GlobalStyle 적용 및 eslint, prettier 설정 일부 수정
  fe/package-lock.json
  fe/package.json
  fe/src/index.js
  fe/src/styles/GlobalStyle.jsx
  fe/src/styles/theme.js
Labels: Setting, FE, Design

#40 [FE] issueTableHeader 컴포넌트 구성 및 레이아웃
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.js
  fe/src/assets/icons/CloseIssueStatusIcon.svg
  fe/src/assets/icons/DropdownIcon.svg
  fe/src/assets/icons/OpenIssueStatusIcon.svg
  fe/src/common/Checkbox.jsx
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueStatusButton.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueTableHeaderLeft.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/index.js
  fe/src/pages/MainPage.jsx
  fe/src/styles/GlobalStyle.jsx
  fe/src/styles/theme.js
Labels: FE, Design

#50 [iOS] 이슈리스트 리팩토링 및 커스텀셀 등록
  iOS/Issue-tracker/.swiftlint.yml
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/Help/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/Help/UIColor+Extension.swift
  iOS/Issue-tracker/Issue-tracker/Help/UIFont+Extension.swift
  iOS/Issue-tracker/Issue-tracker/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/Resource/AppDelegate.swift
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/blue.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray100.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray200.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray300.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray400.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray50.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray500.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray600.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray700.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray800.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/gray900.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/purple.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Color/red.colorset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/레이블.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/레이블.imageset/레이블 2.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/마일스톤.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/마일스톤.imageset/마일스톤 2.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/이슈.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/이슈.imageset/이슈 2.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Base.lproj/Main.storyboard
  iOS/Issue-tracker/Issue-tracker/Resource/SceneDelegate.swift
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
  iOS/Issue-tracker/Issue-tracker/UIFont+Extension.swift
  iOS/Issue-tracker/Podfile.lock
Labels: iOS, Refactoring

#53 [FE] nav 컴포넌트 구성 및 스타일 적용
  fe/src/App.js
  fe/src/assets/icons/PlusIcon.svg
  fe/src/common/button/Button.jsx
  fe/src/common/header/Header.jsx
  fe/src/common/tabs/Tabs.jsx
  fe/src/components/mainPage/nav/Nav.jsx
  fe/src/components/mainPage/nav/filterBar/FilterBar.jsx
  fe/src/pages/MainPage.jsx
Labels: BE, Feature, Design

#54 [FE] mock 데이터 비동기 처리 및 issueTable 스타일
  fe/.eslintrc.json
  fe/public/mockServiceWorker.js
  fe/src/assets/icons/MilestoneIcon.svg
  fe/src/assets/userImage/UserImage.svg
  fe/src/common/header/Header.jsx
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueStatusButton.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueTableHeaderLeft.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/components/mainPage/issueTable/list/IssueTableList.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/Label.jsx
  fe/src/index.js
  fe/src/mocks/handler.js
  fe/src/mocks/worker.js
  fe/src/pages/MainPage.jsx
  fe/src/styles/theme.js
Labels: FE, Feature, Design

#55 [FE] issueMainPage 레이아웃 및 msw 비동기 데이터 처리
  fe/.eslintrc.json
  fe/public/index.html
  fe/public/mockServiceWorker.js
  fe/src/App.js
  fe/src/assets/icons/CloseIssueStatusIcon.svg
  fe/src/assets/icons/DropdownIcon.svg
  fe/src/assets/icons/MilestoneIcon.svg
  fe/src/assets/icons/OpenIssueStatusIcon.svg
  fe/src/assets/icons/PlusIcon.svg
  fe/src/assets/images/logo.svg
  fe/src/assets/images/userImageLarge.svg
  fe/src/assets/userImage/UserImage.svg
  fe/src/common/Checkbox.jsx
  fe/src/common/button/Button.jsx
  fe/src/common/header/Header.jsx
  fe/src/common/tabs/Tabs.jsx
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueStatusButton.jsx
  fe/src/components/mainPage/issueTable/header/headerLeft/IssueTableHeaderLeft.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/components/mainPage/issueTable/list/IssueTableList.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/Label.jsx
  fe/src/components/mainPage/nav/Nav.jsx
  fe/src/components/mainPage/nav/filterBar/FilterBar.jsx
  fe/src/index.js
  fe/src/mocks/handler.js
  fe/src/mocks/worker.js
  fe/src/pages/MainPage.jsx
  fe/src/styles/theme.js
Labels: FE, Feature, Design

#60 [FE] 라우터 설치 및 새로운 이슈작성 페이지 라우터 연결
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/index.js
  fe/src/pages/NewIssuePage.jsx
Labels: FE, Feature

#63 [iOS] 리뷰브랜치와 머지를 위한 pr
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/FilterTableViewController.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
Labels: iOS, Design

#66 [iOS] 2주차 코드리뷰 반영 (이슈레이블 제외)
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/FilterTableViewController.swift
Labels: iOS, Refactoring

#67 [BE] 홈 Issues API 기본 기능 구현
  BE/src/main/java/team01/issuetracker/controller/IssueController.java
  BE/src/main/java/team01/issuetracker/controller/pring/PingController.java
  BE/src/main/java/team01/issuetracker/controller/pring/ResultVO.java
  BE/src/main/java/team01/issuetracker/model/TestResponse.java
  BE/src/main/java/team01/issuetracker/service/IssueService.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssueResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssuesResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/vo/Count.java
  BE/src/main/resources/application.properties
Labels: BE, Feature

#68 [BE] BE2/task2 -> dev/BE2
  BE/src/main/java/team01/issuetracker/controller/IssueController.java
  BE/src/main/java/team01/issuetracker/controller/pring/PingController.java
  BE/src/main/java/team01/issuetracker/controller/pring/ResultVO.java
  BE/src/main/java/team01/issuetracker/model/TestResponse.java
  BE/src/main/java/team01/issuetracker/service/IssueService.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssueResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssuesResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/vo/Count.java
  BE/src/main/resources/application.properties
Labels: BE

#74 [FE] issueTable 영억 코드 리팩토링
  fe/src/App.js
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/headerRight/IssueTableHeaderRight.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterOptions.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateButton.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/ListItemLeft.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/IssueInfo.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/LeftContentBottom.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/IssueTitle.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/Label.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/LeftContentTop.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/ListItemLeftContent.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/ListItemRight.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/UserIcon.jsx
  fe/src/mocks/handler.js
  fe/src/pages/MainPage.jsx
Labels: FE, Refactoring

#79 [BE] BE2/api02 -> dev/BE2
  .gitignore
  BE/README.md
  BE/src/main/java/team01/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team01/issuetracker/config/CorsConfig.java
  BE/src/main/java/team01/issuetracker/controller/AssigneeController.java
  BE/src/main/java/team01/issuetracker/controller/pring/PingController.java
  BE/src/main/java/team01/issuetracker/controller/pring/ResultVO.java
  BE/src/main/java/team01/issuetracker/service/AssigneeService.java
  BE/src/main/java/team01/issuetracker/service/IssueService.java
  BE/src/main/java/team01/issuetracker/service/dto/response/AssigneeResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/AssigneesResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssueResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/vo/Assignee.java
  BE/src/main/java/team01/issuetracker/service/vo/MiniLabel.java
Labels: BE, Feature

#84 [FE] useContext 적용 및 각 컴포넌트 props 수정
  fe/src/components/mainPage/issueTable/IssueTable.jsx
  fe/src/components/mainPage/issueTable/header/IssueTableHeader.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/mainPage/issueTable/list/IssueTableList.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/ListItemLeft.jsx
  fe/src/pages/MainPage.jsx
Labels: FE, Feature

#86 [FE] 이슈 작성 버튼 클릭시 페이지 이동
  fe/src/components/mainPage/nav/Nav.jsx
Labels: FE, Feature

#88 [BE] BE2/api05 -> dev/BE2
  BE/src/main/java/team01/issuetracker/controller/IssueController.java
  BE/src/main/java/team01/issuetracker/service/IssueService.java
  BE/src/main/java/team01/issuetracker/service/dto/request/FilterRequestDTO.java
Labels: BE, Feature

#90 [iOS] 2주차 코드리뷰를 반영한 라이브러리 제거 작업 PR
  iOS/Issue-tracker/.swiftlint.yml
  iOS/Issue-tracker/Issue-tracker/Help/NameSpace.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/PaddingLabel.swift
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/이슈 3.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/레이블 3.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/마일스톤 3.svg
  iOS/Issue-tracker/Issue-tracker/TabBarViewController.swift
  iOS/Issue-tracker/Podfile
Labels: iOS, Refactoring

#91 [iOS] 필터뷰 상단 네비게이션바를 커스텀셀로 구현
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/CustomNaviFilter.swift
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/FilterTableViewController.swift
Labels: iOS, Feature, Design

#92 [FE] api 연결 및 데이터 구조 변경으로 인한 refactor
  fe/.gitignore
  fe/src/App.js
  fe/src/components/common/layout/PageLayout.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/mainPage/issueTable/list/listItems/IssueTableListItem.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/Label.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentTop/LeftContentTop.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/ListItemRight.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemRight/UserIcon.jsx
  fe/src/components/mainPage/nav/Nav.jsx
  fe/src/mocks/handler.js
  fe/src/pages/AddIssuePage.jsx
  fe/src/pages/MainPage.jsx
  fe/src/pages/NewIssuePage.jsx
  fe/src/utils/api/api.js
Labels: FE, Feature, Refactoring

#94 [FE] 드롭다운 컴포넌트 적용 및 비동기 처리
  fe/src/assets/icons/DropdownIcon.svg
  fe/src/components/common/dropdown/Dropdown.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownButton.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownPanel.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterButton.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterOptions.jsx
  fe/src/components/mainPage/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/ListItemLeft.jsx
  fe/src/mocks/handler.js
Labels: FE, Feature

#95 [BE] BE2/api06 -> dev/BE2 & mySQL db 기본세팅
  .gitignore
  BE/build.gradle
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE, Refactoring

#98 [iOS] 오픈라벨 네트워킹 적용 (이슈리스트)
  iOS/Issue-tracker/Issue-tracker.xcodeproj/project.pbxproj
  iOS/Issue-tracker/Issue-tracker/Help/UIColor+Extension.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/issueImage.imageset/이슈 4.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/labelImage.imageset/레이블 4.svg
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/Contents.json
  iOS/Issue-tracker/Issue-tracker/Resource/Assets.xcassets/milestoneImage.imageset/마일스톤 4.svg
  iOS/Issue-tracker/Podfile.lock
Labels: iOS, Feature

#99 feat: cell spacing 구현
  iOS/Issue-tracker/Issue-tracker/IssueList/CollectionHeaderView.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
Labels: iOS, Feature

#100 [FE] 새로운 이슈 작성 페이지 레이아웃
  fe/src/assets/icons/CancelIcon.svg
  fe/src/components/addIssuePage/addIssueButtons/Buttons.jsx
  fe/src/components/addIssuePage/addIssueMainContent/AddIssueMainContent.jsx
  fe/src/components/addIssuePage/addIssueMainContent/Inputs.jsx
  fe/src/components/addIssuePage/addIssueMainContent/Sidebar.jsx
  fe/src/components/common/button/Button.jsx
  fe/src/components/common/layout/PageLayout.jsx
  fe/src/components/mainPage/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/LeftContentBottom.jsx
  fe/src/index.js
  fe/src/pages/AddIssuePage.jsx
  fe/src/pages/MainPage.jsx
  fe/src/styles/GlobalStyle.jsx
  fe/src/utils/api/timeElapsed.js
Labels: FE, Feature, Design

#101 [FE] dropdown 추가 작업
  fe/src/assets/icons/CheckOffCircle.svg
  fe/src/assets/icons/CheckOnCircle.svg
  fe/src/components/common/dropdown/Dropdown.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownPanel.jsx
  fe/src/components/mainPage/issueTable/header/issueFilterOptions/IssueFilterOptions.jsx
Labels: FE, Feature, Design

#123 [FE] 메인페이지 드롭다운 구현 및 이슈 목록 필터 적용
  fe/.eslintrc.json
  fe/package-lock.json
  fe/src/assets/icons/CheckOnCircle.svg
  fe/src/components/common/dropdown/dropdownContent/DropdownButton.jsx
  fe/src/components/common/dropdown/dropdownContent/DropdownPanel.jsx
  fe/src/components/common/dropdown/dropdownContent/dropdownBody/index.jsx
  fe/src/components/common/dropdown/dropdownContent/dropdownBody/style.js
  fe/src/components/common/dropdown/dropdownContent/dropdownButton/index.jsx
  fe/src/components/common/dropdown/dropdownContent/dropdownButton/style.js
  fe/src/components/common/dropdown/dropdownContent/dropdownPanel/index.jsx
  fe/src/components/common/dropdown/dropdownContent/dropdownPanel/style.js
  fe/src/components/common/dropdown/index.jsx
  fe/src/components/common/dropdown/style.js
  fe/src/components/common/icon/UserIcon.jsx
  fe/src/components/issueList/issueTable/header/issueFilterOptions/IssueFilterOptions.jsx
  fe/src/components/issueList/issueTable/header/issueStateFilter/IssueStateFilter.jsx
  fe/src/components/issueList/issueTable/list/IssueTableList.jsx
  fe/src/components/issueList/issueTable/list/listItems/listItemLeft/listItemLeftContent/LeftContentBottom/LeftContentBottom.jsx
  fe/src/components/issueList/issueTable/list/listItems/listItemRight/ListItemRight.jsx
  fe/src/pages/IssueList.jsx
Labels: FE, Feature

#124 [FE] 이슈 상세페이지 컴포넌트 및 스타일 작업, 상태 처리
  fe/src/assets/icons/EditIcon.svg
  fe/src/assets/icons/archiveIcon.svg
  fe/src/components/common/button/index.jsx
  fe/src/components/common/button/style.js
  fe/src/components/common/inputText/index.jsx
  fe/src/components/common/inputText/style.js
  fe/src/components/common/lable/index.jsx
  fe/src/components/common/lable/style.js
  fe/src/components/issueDetail/detailContent/index.jsx
  fe/src/components/issueDetail/detailContent/style.js
  fe/src/components/issueDetail/detailHeader/index.jsx
  fe/src/components/issueDetail/detailHeader/style.js
  fe/src/pages/IssueDetail.jsx
Labels: FE, Feature, Refactoring
