Repository issue-tracker-team-01/issue-tracker, pull requests merged in 2023-06, with the labels that each got.

#127 [iOS] 필터 로직 구현
  iOS/Issue-tracker/Issue-tracker/FilterIssueTable/FilterTableViewController.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueCell.swift
  iOS/Issue-tracker/Issue-tracker/IssueList/IssueListCollectionViewController.swift
  iOS/Issue-tracker/Issue-tracker/Network/IssueData.swift
  iOS/Issue-tracker/Issue-tracker/Network/NetworkManager.swift
  iOS/Issue-tracker/Issue-tracker/Network/PrivateURL.swift
Labels: iOS, Feature

#132 [BE] 최종 작업
  BE/src/main/java/team01/issuetracker/config/CorsConfig.java
  BE/src/main/java/team01/issuetracker/controller/AssigneeController.java
  BE/src/main/java/team01/issuetracker/controller/IssueController.java
  BE/src/main/java/team01/issuetracker/controller/LabelController.java
  BE/src/main/java/team01/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team01/issuetracker/controller/WriterController.java
  BE/src/main/java/team01/issuetracker/domain/Issue.java
  BE/src/main/java/team01/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssueDetailResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssueResponseDTO.java
  BE/src/main/java/team01/issuetracker/service/dto/response/IssuesResponseDTO.java
  BE/src/main/resources/application.properties
Labels: BE, Fix, Refactoring

#135 [FE] design: textArea 스타일 수정
  fe/src/components/common/button/style.js
  fe/src/components/common/textArea/index.jsx
  fe/src/components/common/textArea/style.js
Labels: FE, Design

#137 [Fe/issue detail
  fe/src/components/common/inputText/index.jsx
  fe/src/components/issueDetail/detailHeader/index.jsx
  fe/src/pages/IssueDetail.jsx
Labels: Feature

#138 [FE] design: 스타일 추가 리팩토링
  fe/src/components/common/label/style.js
  fe/src/components/common/textArea/style.js
  fe/src/components/issueDetail/detailContent/index.jsx
  fe/src/components/issueDetail/detailContent/style.js
  fe/src/components/issueDetail/detailHeader/index.jsx
  fe/src/pages/IssueDetail.jsx
Labels: FE, Design

#139 [FE] 웹서버 배포를 위한 추가 파일 커밋
  .github/workflows/relese-fe.yml
  appspec.yml
  scripts/deployFE.sh
Labels: Setting, FE
